# Quantitative Momentum Strategy

"Momentum investing" means investing in the stocks that have increased in price the most.

For this project, we're going to build an investing strategy that selects the 50 stocks with the highest price momentum. From there, we will calculate recommended trades for an equal-weight portfolio of these 50 stocks.


## Library Imports

The first thing we need to do is import the open-source software libraries that we'll be using in this tutorial.

In [159]:
import numpy as np
import pandas as pd
import requests
import math
from scipy.stats import percentileofscore as score
import xlsxwriter

## Importing Our List of Stocks

As before, we'll need to import our list of stocks and our API token before proceeding.

In [51]:
from secrets import IEX_CLOUD_API_TOKEN
stocks=pd.read_csv("sp_500_stocks.csv")

## Making Our First API Call

It's now time to make the first version of our momentum screener!

We need to get one-year price returns for each stock in the universe. Here's how.

In [52]:
symbol="AAPL"
stat_1yearChangePercent = "0.39751716851558366"

## Remember to input ""/stable", because IEX cloud documentation states it in the beginning
## Remember "?token=IEX_CLOUD_API_TOKEN" at the end for authentification
api_url = f"https://sandbox.iexapis.com/stable/stock/{symbol}/stats?token={IEX_CLOUD_API_TOKEN}"

data = requests.get(api_url).json()
data

{'companyName': 'Apple Inc',
 'marketcap': 2212141582230,
 'week52high': 135.41,
 'week52low': 56.24,
 'week52change': 0.8378922638512776,
 'sharesOutstanding': 17077046685,
 'float': 0,
 'avg10Volume': 129235803,
 'avg30Volume': 107582227,
 'day200MovingAvg': 110.36,
 'day50MovingAvg': 123.09,
 'employees': 0,
 'ttmEPS': 3.31,
 'ttmDividendRate': 0.8276088724827838,
 'dividendYield': 0.006472519791000138,
 'nextDividendDate': '0',
 'exDividendDate': '2020-10-29',
 'nextEarningsDate': '0',
 'peRatio': 38.79957726097349,
 'beta': 1.196985370164775,
 'maxChangePercent': 50.41227196702309,
 'year5ChangePercent': 4.239403209528756,
 'year2ChangePercent': 2.518205919374131,
 'year1ChangePercent': 0.8735543557100228,
 'ytdChangePercent': 0.7693655394253508,
 'month6ChangePercent': 0.4776412204643289,
 'month3ChangePercent': 0.1750732732022205,
 'month1ChangePercent': 0.09358389830864937,
 'day30ChangePercent': 0.09596191310018778,
 'day5ChangePercent': 0.05434643494369141}

## Parsing Our API Call

This API call has all the information we need. We can parse it using the same square-bracket notation as in the first project of this course. Here is an example.

In [53]:
data["year1ChangePercent"]

0.8735543557100228

## Executing A Batch API Call & Building Our DataFrame

Just like in the first project, it's now time to execute several batch API calls and add the information we need to our DataFrame.

We'll start by running the following code cell, which contains some code we already built last time that we can re-use for this project. More specifically, it contains a function called `chunks` that we can use to divide our list of securities into groups of 100.

In [54]:
##Credits, Ned Batchelder: https://stackoverflow.com/questions/312443/how-do-you-split-a-list-into-evenly-sized-chunks
def chunks(lst, n):
    """Yield successive n-sized chunks from lst."""
    for i in range(0, len(lst), n):
        yield lst[i:i + n]   
        
symbol_groups = list(chunks(stocks['Ticker'], 100))
symbol_strings = []
for i in range(0, len(symbol_groups)):
    symbol_strings.append(','.join(symbol_groups[i]))
#    print(symbol_strings[i])

my_columns = ['Ticker', 'Price', 'One-Year Price Return', 'Number of Shares to Buy']

Now we need to create a blank DataFrame and add our data to the data frame one-by-one.

In [104]:
final_df = pd.DataFrame(columns=my_columns)

for symbol_string in symbol_strings:
    
    ## "types" is the API endpoint url, which is also written down in the IEX cloud API documentation
    batch_api_call_url = f"https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}"
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(","):
        final_df = final_df.append(
            pd.Series(
                [
                    ## LOOK AT "batch_api_call_url". Notice how after batch, the order is "symbols", then "stats". THIS is why you have to parse by symbol first and then stats in the data
                    symbol,
                    data[symbol]["price"],
                    data[symbol]["stats"]["year1ChangePercent"],
                    "N/A"
                ],
                index=my_columns),
                ignore_index=True
                )
final_df

    Ticker   Price One-Year Price Return Number of Shares to Buy
0        A  121.98              0.397621                     N/A
1      AAL   16.20             -0.452779                     N/A
2      AAP  162.21             0.0235604                     N/A
3     AAPL  130.13              0.871619                     N/A
4     ABBV  105.44              0.226255                     N/A
..     ...     ...                   ...                     ...
500    YUM  110.65              0.105172                     N/A
501    ZBH  150.50           -0.00370353                     N/A
502   ZBRA  379.07              0.505634                     N/A
503   ZION   44.54             -0.148092                     N/A
504    ZTS  163.19              0.227153                     N/A

[505 rows x 4 columns]

## Removing Low-Momentum Stocks

The investment strategy that we're building seeks to identify the 50 highest-momentum stocks in the S&P 500.

Because of this, the next thing we need to do is remove all the stocks in our DataFrame that fall below this momentum threshold. We'll sort the DataFrame by the stocks' one-year price return, and drop all stocks outside the top 50.

In [105]:
## Sort the dataframe by "One-Year Price Return", so that the highest momentum stocks are the top (ascending=False)
final_df.sort_values("One-Year Price Return", ascending = False, inplace = True)
final_df = final_df[:50]

## Resetting index so the dataframe does not have random numbers for indices
final_df.reset_index(inplace = True)
final_df

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0      78   CARR    38.69               2.27992                     N/A
1     345   NVDA   552.27               1.25928                     N/A
2     387   PYPL   239.57               1.18763                     N/A
3      31    AMD    97.12               1.15698                     N/A
4     275     LB    39.23               1.12485                     N/A
5      23    ALB   144.21               1.08278                     N/A
6     179    FCX    25.56                1.0088                     N/A
7      24   ALGN   552.38              0.990139                     N/A
8     339    NOW   563.21              0.978132                     N/A
9      85   CDNS   133.92              0.912083                     N/A
10    236   IDXX   493.75              0.905785                     N/A
11    180    FDX   272.51               0.87408                     N/A
12      3   AAPL   130.13              0.871619                     N/A
13    490    WST   277.07              0.844172                     N/A
14      6   ABMD   300.21              0.836923                     N/A
15    415   SNPS   260.85              0.828198                     N/A
16    400    ROL    41.07              0.826183                     N/A
17     36   AMZN  3231.75              0.806515                     N/A
18    440   TMUS   132.06              0.737442                     N/A
19    448   TWTR    55.52              0.729211                     N/A
20    101    CMG  1435.54              0.721591                     N/A
21    358   PAYC   448.80              0.714177                     N/A
22    319   MSCI   455.48              0.713717                     N/A
23    388   QCOM   152.30              0.710167                     N/A
24    385    PWR    69.27              0.672482                     N/A
25     13   ADSK   308.11              0.668712                     N/A
26    288   LRCX   488.37              0.666376                     N/A
27    447   TTWO   210.01               0.64814                     N/A
28    444   TSCO   150.86              0.644046                     N/A
29    150   DXCM   365.81              0.643593                     N/A
30     63    BIO   619.75              0.609336                     N/A
31    351   ODFL   200.64               0.60671                     N/A
32    147    DVA   120.39              0.577982                     N/A
33    128     DE   275.36              0.572521                     N/A
34    332   NFLX   546.90              0.571558                     N/A
35    308   MKTX   581.99              0.564884                     N/A
36    246   IPGP   226.84              0.537201                     N/A
37     48   ATVI    91.38              0.533676                     N/A
38    331    NEM    61.78              0.531948                     N/A
39      9   ADBE   506.22              0.531644                     N/A
40    461    UPS   179.73              0.528898                     N/A
41    266   KLAC   270.25              0.516163                     N/A
42    495   XLNX   151.24              0.512029                     N/A
43    502   ZBRA   379.07              0.505634                     N/A
44    133    DHR   235.45               0.49487                     N/A
45    410   SIVB   384.00              0.477136                     N/A
46    356   OTIS    67.88              0.468026                     N/A
47    372    PKI   146.85               0.46514                     N/A
48    223   HOLX    75.87              0.463685                     N/A
49    335   NLOK    21.83              0.460476                     N/A

## Calculating the Number of Shares to Buy

Just like in the last project, we now need to calculate the number of shares we need to buy. The one change we're going to make is wrapping this functionality inside a function, since we'll be using it again later in this Jupyter Notebook.

Since we've already done most of the work on this, try to complete the following two code cells without watching me do it first!

In [106]:
def portfolio_input():
    global portfolio_size
    portfolio_size = input("Enter the size of your portfolio: ")
    
    try:
        float(portfolio_size)
    except ValueError:
        print("That is not an integer.\nPlease try again.")
        portfolio_size = input("Enter the size of your portfolio: ")

portfolio_input()
print(portfolio_size)

Enter the size of your portfolio: 100000000000
100000000000

In [107]:
## Fill in the N/A of "Number of Shares to Buy" as an equal weight portfolio of the 50 stocks
position_size = float(portfolio_size)/len(final_df.index)
        
for i in range(len(final_df)):
    ## Notice how the "math.floor" function is put at the beginning
    final_df.loc[i, "Number of Shares to Buy"] = math.floor(position_size/final_df.loc[i, "Price"])
    
final_df

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

    index Ticker    Price One-Year Price Return Number of Shares to Buy
0      78   CARR    38.69               2.27992                51692943
1     345   NVDA   552.27               1.25928                 3621417
2     387   PYPL   239.57               1.18763                 8348290
3      31    AMD    97.12               1.15698                20593080
4     275     LB    39.23               1.12485                50981391
5      23    ALB   144.21               1.08278                13868663
6     179    FCX    25.56                1.0088                78247261
7      24   ALGN   552.38              0.990139                 3620695
8     339    NOW   563.21              0.978132                 3551073
9      85   CDNS   133.92              0.912083                14934289
10    236   IDXX   493.75              0.905785                 4050632
11    180    FDX   272.51               0.87408                 7339180
12      3   AAPL   130.13              0.871619                15369246
13    490    WST   277.07              0.844172                 7218392
14      6   ABMD   300.21              0.836923                 6662003
15    415   SNPS   260.85              0.828198                 7667241
16    400    ROL    41.07              0.826183                48697345
17     36   AMZN  3231.75              0.806515                  618859
18    440   TMUS   132.06              0.737442                15144631
19    448   TWTR    55.52              0.729211                36023054
20    101    CMG  1435.54              0.721591                 1393203
21    358   PAYC   448.80              0.714177                 4456327
22    319   MSCI   455.48              0.713717                 4390972
23    388   QCOM   152.30              0.710167                13131976
24    385    PWR    69.27              0.672482                28872527
25     13   ADSK   308.11              0.668712                 6491188
26    288   LRCX   488.37              0.666376                 4095255
27    447   TTWO   210.01               0.64814                 9523356
28    444   TSCO   150.86              0.644046                13257324
29    150   DXCM   365.81              0.643593                 5467319
30     63    BIO   619.75              0.609336                 3227107
31    351   ODFL   200.64               0.60671                 9968102
32    147    DVA   120.39              0.577982                16612675
33    128     DE   275.36              0.572521                 7263219
34    332   NFLX   546.90              0.571558                 3656975
35    308   MKTX   581.99              0.564884                 3436485
36    246   IPGP   226.84              0.537201                 8816787
37     48   ATVI    91.38              0.533676                21886627
38    331    NEM    61.78              0.531948                32372936
39      9   ADBE   506.22              0.531644                 3950851
40    461    UPS   179.73              0.528898                11127802
41    266   KLAC   270.25              0.516163                 7400555
42    495   XLNX   151.24              0.512029                13224014
43    502   ZBRA   379.07              0.505634                 5276070
44    133    DHR   235.45               0.49487                 8494372
45    410   SIVB   384.00              0.477136                 5208333
46    356   OTIS    67.88              0.468026                29463759
47    372    PKI   146.85               0.46514                13619339
48    223   HOLX    75.87              0.463685                26360880
49    335   NLOK    21.83              0.460476                91617040

## Building a Better (and More Realistic) Momentum Strategy

Real-world quantitative investment firms differentiate between "high quality" and "low quality" momentum stocks:

* High-quality momentum stocks show "slow and steady" outperformance over long periods of time
* Low-quality momentum stocks might not show any momentum for a long time, and then surge upwards.

The reason why high-quality momentum stocks are preferred is because low-quality momentum can often be cause by short-term news that is unlikely to be repeated in the future (such as an FDA approval for a biotechnology company).

To identify high-quality momentum, we're going to build a strategy that selects stocks from the highest percentiles of: 

* 1-month price returns
* 3-month price returns
* 6-month price returns
* 1-year price returns

Let's start by building our DataFrame. You'll notice that I use the abbreviation `hqm` often. It stands for `high-quality momentum`.

In [253]:
hqm_columns = [
    "Ticker",
    "Price",
    "Number of Shares to Buy",
    "1-Year Price Return",
    "1-Year Return Percentile",
    "6-Month Price Return",
    "6-Month Return Percentile",
    "3-Month Price Return",
    "3-Month Return Percentile",
    "1-Month Price Return",
    "1-Month Return Percentile",
    "HQM Score"
]
hqm_df = pd.DataFrame(columns=hqm_columns)

for symbol_string in symbol_strings:
    batch_api_call_url = batch_api_call_url = f"https://sandbox.iexapis.com/stable/stock/market/batch?symbols={symbol_string}&types=price,stats&token={IEX_CLOUD_API_TOKEN}"
    data = requests.get(batch_api_call_url).json()
    for symbol in symbol_string.split(","):
        hqm_df = hqm_df.append(
            pd.Series
(
                [
                    symbol,
                    data[symbol]["price"] ,
                    "N/A",
                    data[symbol]["stats"]["year1ChangePercent"],
                    "N/A",
                    data[symbol]["stats"]["month6ChangePercent"],
                    "N/A",
                    data[symbol]["stats"]["month3ChangePercent"],
                    "N/A",
                    data[symbol]["stats"]["month1ChangePercent"],
                    "N/A",
                    "N/A"
                ],
            index=hqm_columns),
            ignore_index=True)

hqm_df

,Ticker,Price,Number of Shares to Buy,1-Year Price Return,1-Year Return Percentile,6-Month Price Return,6-Month Return Percentile,3-Month Price Return,3-Month Return Percentile,1-Month Price Return,1-Month Return Percentile,HQM Score
0,A,120.225,N/A,0.413425,N/A,0.344252,N/A,0.20544,N/A,0.0634421,N/A,N/A
1,AAL,16.200,N/A,-0.453803,N/A,0.00626514,N/A,0.324028,N/A,0.289791,N/A,N/A
2,AAP,159.810,N/A,0.0231532,N/A,0.111254,N/A,0.0832367,N/A,0.11627,N/A,N/A
3,AAPL,136.230,N/A,0.872924,N/A,0.487701,N/A,0.174909,N/A,0.0963017,N/A,N/A
4,ABBV,103.927,N/A,0.226008,N/A,0.103558,N/A,0.18449,N/A,0.0288201,N/A,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,111.020,N/A,0.105025,N/A,0.243424,N/A,0.225197,N/A,0.0403643,N/A,N/A
501,ZBH,152.229,N/A,-0.00364234,N/A,0.190315,N/A,0.111619,N/A,0.0184822,N/A,N/A
502,ZBRA,396.980,N/A,0.502475,N/A,0.439709,N/A,0.523016,N/A,0.0617785,N/A,N/A
503,ZION,42.920,N/A,-0.148012,N/A,0.207031,N/A,0.436532,N/A,0.110088,N/A,N/A
504,ZTS,168.340,N/A,0.223188,N/A,0.17631,N/A,0.000448022,N/A,-0.0337012,N/A,N/A

## Calculating Momentum Percentiles

We now need to calculate momentum percentile scores for every stock in the universe. More specifically, we need to calculate percentile scores for the following metrics for every stock:

* `One-Year Price Return`
* `Six-Month Price Return`
* `Three-Month Price Return`
* `One-Month Price Return`

Here's how we'll do this:

In [254]:
## Declaring the "time_periods" variable so we can use string interpolation to loop through the momentum percentiles instead of going each each one one-by-one
time_periods = [
                "1-Year",
                "6-Month",
                "3-Month",
                "1-Month",
                ]

for row in hqm_df.index:
    for time_period in time_periods:
        ## Using the "scipy" library's "percentiles_of_score" to get the percentile for each "time_period"
        change_col = f"{time_period} Price Return"
        per_col = f"{time_period} Return Percentile"
        ## Error says ""'<' not supported between instances of 'NoneType' and 'float", so that means there are instances
        ## where the script is trying to compare a "NoneType" and a "float", so we make sure that does not happen
        if hqm_df.loc[row, per_col] == None:
            hqm_df.loc[row, per_col] = 0.0
        if hqm_df.loc[row, change_col] == None:
            hqm_df.loc[row, change_col] = 0.0

## The double for-loops have to be run seperately for some reason
for row in hqm_df.index:
    for time_period in time_periods:

        change_col = f"{time_period} Price Return"
        per_col = f"{time_period} Return Percentile"   
        ## Using the "scipy" library's "percentiles_of_score" to get the percentile for each "time_period"
        ##We create the percentile score for for each stock and each timeperiod
        hqm_df.loc[row, per_col] = score(hqm_df[change_col], hqm_df.loc[row, change_col])/100
                
        
hqm_df

,Ticker,Price,Number of Shares to Buy,1-Year Price Return,1-Year Return Percentile,6-Month Price Return,6-Month Return Percentile,3-Month Price Return,3-Month Return Percentile,1-Month Price Return,1-Month Return Percentile,HQM Score
0,A,120.225,N/A,0.413425,0.869307,0.344252,0.732673,0.20544,0.588119,0.0634421,0.677228,N/A
1,AAL,16.200,N/A,-0.453803,0.0237624,0.00626514,0.136634,0.324028,0.821782,0.289791,0.992079,N/A
2,AAP,159.810,N/A,0.0231532,0.429703,0.111254,0.30099,0.0832367,0.29703,0.11627,0.855446,N/A
3,AAPL,136.230,N/A,0.872924,0.978218,0.487701,0.893069,0.174909,0.514851,0.0963017,0.80396,N/A
4,ABBV,103.927,N/A,0.226008,0.70495,0.103558,0.285149,0.18449,0.534653,0.0288201,0.485149,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,111.020,N/A,0.105025,0.554455,0.243424,0.580198,0.225197,0.635644,0.0403643,0.562376,N/A
501,ZBH,152.229,N/A,-0.00364234,0.382178,0.190315,0.451485,0.111619,0.376238,0.0184822,0.407921,N/A
502,ZBRA,396.980,N/A,0.502475,0.914851,0.439709,0.845545,0.523016,0.956436,0.0617785,0.661386,N/A
503,ZION,42.920,N/A,-0.148012,0.20396,0.207031,0.49505,0.436532,0.918812,0.110088,0.845545,N/A
504,ZTS,168.340,N/A,0.223188,0.70099,0.17631,0.427723,0.000448022,0.124752,-0.0337012,0.108911,N/A

## Calculating the HQM Score

We'll now calculate our `HQM Score`, which is the high-quality momentum score that we'll use to filter for stocks in this investing strategy.

The `HQM Score` will be the arithmetic mean of the 4 momentum percentile scores that we calculated in the last section.

To calculate arithmetic mean, we will use the `mean` function from Python's built-in `statistics` module.

In [255]:
from statistics import mean


for row in hqm_df.index:
    momentum_percentiles = []
    for time_period in time_periods:
        momentum_percentiles.append(hqm_df.loc[row, f"{time_period} Return Percentile"])
    hqm_df.loc[row, "HQM Score"] = mean(momentum_percentiles)
    
hqm_df

,Ticker,Price,Number of Shares to Buy,1-Year Price Return,1-Year Return Percentile,6-Month Price Return,6-Month Return Percentile,3-Month Price Return,3-Month Return Percentile,1-Month Price Return,1-Month Return Percentile,HQM Score
0,A,120.225,N/A,0.413425,0.869307,0.344252,0.732673,0.20544,0.588119,0.0634421,0.677228,0.716832
1,AAL,16.200,N/A,-0.453803,0.0237624,0.00626514,0.136634,0.324028,0.821782,0.289791,0.992079,0.493564
2,AAP,159.810,N/A,0.0231532,0.429703,0.111254,0.30099,0.0832367,0.29703,0.11627,0.855446,0.470792
3,AAPL,136.230,N/A,0.872924,0.978218,0.487701,0.893069,0.174909,0.514851,0.0963017,0.80396,0.797525
4,ABBV,103.927,N/A,0.226008,0.70495,0.103558,0.285149,0.18449,0.534653,0.0288201,0.485149,0.502475
...,...,...,...,...,...,...,...,...,...,...,...,...
500,YUM,111.020,N/A,0.105025,0.554455,0.243424,0.580198,0.225197,0.635644,0.0403643,0.562376,0.583168
501,ZBH,152.229,N/A,-0.00364234,0.382178,0.190315,0.451485,0.111619,0.376238,0.0184822,0.407921,0.404455
502,ZBRA,396.980,N/A,0.502475,0.914851,0.439709,0.845545,0.523016,0.956436,0.0617785,0.661386,0.844554
503,ZION,42.920,N/A,-0.148012,0.20396,0.207031,0.49505,0.436532,0.918812,0.110088,0.845545,0.615842
504,ZTS,168.340,N/A,0.223188,0.70099,0.17631,0.427723,0.000448022,0.124752,-0.0337012,0.108911,0.340594

## Selecting the 50 Best Momentum Stocks

As before, we can identify the 50 best momentum stocks in our universe by sorting the DataFrame on the `HQM Score` column and dropping all but the top 50 entries.

In [256]:
hqm_df.sort_values("HQM Score", ascending=False, inplace=True)
## Selecting top 50
hqm_df = hqm_df[:50]
hqm_df.reset_index(inplace=True, drop=True)

## Calculating the Number of Shares to Buy

We'll use the `portfolio_input` function that we created earlier to accept our portfolio size. Then we will use similar logic in a `for` loop to calculate the number of shares to buy for each stock in our investment universe.

In [257]:
portfolio_input()

Enter the size of your portfolio: 100000000000

In [258]:
position_size = math.floor(float(portfolio_size)/len(hqm_df.index))
for i in hqm_df.index:
    hqm_df.loc[i, "Number of Shares to Buy"] = math.floor(position_size/hqm_df.loc[i, "Price"])

hqm_df.head()

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

,Ticker,Price,Number of Shares to Buy,1-Year Price Return,1-Year Return Percentile,6-Month Price Return,6-Month Return Percentile,3-Month Price Return,3-Month Return Percentile,1-Month Price Return,1-Month Return Percentile,HQM Score
0,ALGN,546.760,3657912,0.961794,0.984158,1.05139,0.994059,0.674241,0.990099,0.194381,0.960396,0.982178
1,FCX,25.467,78533003,1.00807,0.988119,1.3745,0.99802,0.614814,0.978218,0.173353,0.934653,0.974752
2,ALB,146.650,13637913,1.07875,0.990099,0.855391,0.984158,0.509674,0.954455,0.118179,0.863366,0.94802
3,TWTR,54.910,36423238,0.726149,0.962376,0.645677,0.952475,0.384727,0.891089,0.227493,0.974257,0.94505
4,LRCX,483.990,4132316,0.654216,0.944554,0.554582,0.930693,0.568502,0.968317,0.117921,0.861386,0.926238

## Formatting Our Excel Output

We will be using the XlsxWriter library for Python to create nicely-formatted Excel files.

XlsxWriter is an excellent package and offers tons of customization.

In [259]:
writer = pd.ExcelWriter("Momentum_Strategy.xlsx", engine="xlsxwriter")
hqm_df.to_excel(writer, sheet_name = "Momentum Strategy", index=False)

## Creating the Formats We'll Need For Our .xlsx File

You'll recall from our first project that formats include colors, fonts, and also symbols like % and $. We'll need four main formats for our Excel document:

* String format for tickers
* \$XX.XX format for stock prices
* \$XX,XXX format for market capitalization
* Integer format for the number of shares to purchase

Since we already built our formats in the last section of this course, I've included them below for you. Run this code cell before proceeding.

In [260]:
background_color = '#0a0a23'
font_color = '#ffffff'

string_template = writer.book.add_format(
        {
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

dollar_template = writer.book.add_format(
        {
            'num_format':'$0.00',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

integer_template = writer.book.add_format(
        {
            'num_format':'0',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

percent_template = writer.book.add_format(
        {
            'num_format':'0.0%',
            'font_color': font_color,
            'bg_color': background_color,
            'border': 1
        }
    )

In [261]:
column_templates={
    "A" : ["Ticker", string_template],
    "B" : ["Price", dollar_template],
    "C" : ["Number of Shares to Buy", integer_template],
    "D" : ["1-Year Price Return", percent_template],
    "E" : ["1-Year Return Percentile", percent_template],
    "F" : ["6-Month Price Return",percent_template],
    "G" : ["6-Month Return Percentile",percent_template],
    "H" : ["3-Month Price Return",percent_template],
    "I" : ["3-Month Return Percentile",percent_template],
    "J" : ["1-Month Price Return",percent_template],
    "K" : ["1-Month Return Percentile",percent_template],
    "L" : ["HQM Score", percent_template]
}


for column in column_templates.keys():
    writer.sheets["Momentum Strategy"].set_column(f"{column}:{column}", 25, column_templates[column][1])
    writer.sheets["Momentum Strategy"].write(f"{column}1", column_templates[column][0], column_templates[column][1])

## Saving Our Excel Output

As before, saving our Excel output is very easy:

In [262]:
writer.save()